on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: programmingwithalex/pylinters@v1.4.2
      with:
        python-root: '.'
        flake8-flags: '--max-line-length 120'
        mypy-flags: '--ignore-missing-imports'
        fail-on-isort: true

    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
